# Generated by Django 5.2.7 on 2025-10-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Phúc lợi'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng tuyển'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mức lương'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
