# Generated by Django 5.2.7 on 2025-10-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_notes', models.TextField(verbose_name='Ghi chú của HR (Câu trả lời của UV)')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='Phân tích chi tiết từ AI')),
                ('ai_score', models.IntegerField(default=0, verbose_name='Điểm phỏng vấn từ AI')),
                ('interview_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phỏng vấn')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application', verbose_name='Hồ sơ ứng tuyển')),
            ],
        ),
    ]
