# Generated by Django 5.2.7 on 2025-10-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_question_answer_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link hành động'),
        ),
    ]
