# Generated by Django 5.2.7 on 2025-10-13 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_notification_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Trắc nghiệm'), ('ESSAY', 'Tự luận')], default='MC', max_length=5),
        ),
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.question')),
            ],
        ),
    ]
