# Generated by Django 5.2.7 on 2025-10-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_question_question_type_essayanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='time_limit',
            field=models.PositiveIntegerField(default=15, verbose_name='Thời gian làm bài (phút)'),
        ),
    ]
