# Generated by Django 5.2.7 on 2025-10-13 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_jobposting_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt bản thân')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='Kinh nghiệm làm việc')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Học vấn')),
                ('skills', models.TextField(blank=True, verbose_name='Các kỹ năng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
