# Generated by Django 5.2.7 on 2025-10-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_cvprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVProfile',
        ),
    ]
