# Generated by Django 5.2.5 on 2025-10-15 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_delete_cvprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='recruitment.jobposting'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Tóm tắt bản thân'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Trắc nghiệm'), ('ESSAY', 'Tự luận')], default='MC', max_length=10),
        ),
    ]
