# Generated by Django 5.2.5 on 2025-10-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_alter_application_job_alter_profile_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='application',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='application',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='EssayAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
