# Generated by Django 5.2.5 on 2025-10-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_alter_application_job_alter_profile_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt bản thân'),
        ),
    ]
