# Generated by Django 5.2.5 on 2025-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_essayanswer_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('invited', 'Đã mời phỏng vấn'), ('confirmed', 'Đã xác nhận phỏng vấn'), ('rejected', 'Đã từ chối')], default='pending', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
