# Generated by Django 5.2.5 on 2025-11-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('invited', 'Đã mời phỏng vấn'), ('confirmed', 'Đã xác nhận phỏng vấn'), ('rejected', 'Đã từ chối'), ('passed', 'Đã trúng tuyển')], default='pending', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
