# Generated by Django 5.2.5 on 2025-11-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('IT', 'Công nghệ thông tin'), ('BA', 'Business Analyst'), ('Tester', 'Kiểm thử phần mềm'), ('HR', 'Nhân sự'), ('Marketing', 'Marketing'), ('Sales', 'Kinh doanh'), ('Other', 'Khác')], default='Other', max_length=50, verbose_name='Ngành nghề'),
        ),
    ]
