# Generated by Django 5.2.5 on 2025-11-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_jobposting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Đã lưu trữ '),
        ),
    ]
