# Generated by Django 5.2.5 on 2025-11-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_remove_jobposting_time_limit_jobposting_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
