from django.urls import path
from . import views

urlpatterns = [
    path('', views.job_list_view, name='job_list'), 
    path('login/', views.login_view, name='login'),
    path('jobs/', views.job_board_view, name='job_board'),
    path('<int:job_id>/', views.job_detail, name='job_detail'),
    path('create/', views.create_job, name='create_job'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('<int:job_id>/analyze/', views.analyze_cv_view, name='analyze_cv'),
    path('<int:job_id>/applicants/', views.applicant_list_view, name='applicant_list'),
    path('dashboard/', views.recruiter_dashboard, name='recruiter_dashboard'),
    path('application/<int:application_id>/interview-questions/', views.generate_interview_questions, name='interview_questions'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('api/chat/', views.chat_api_view, name='chat_api'),
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('api/chat/', views.chat_api_view, name='chat_api'),
    path('search-candidates/', views.search_candidates_view, name='search_candidates'),
    path('job-matches/', views.job_match_view, name='job_matches'),
    path('apply-with-profile/<int:job_id>/', views.apply_with_profile_view, name='apply_with_profile'),
    path('create/review/', views.create_job_review, name='create_job_review'),
    path('job/<int:job_id>/delete/', views.delete_job_view, name='delete_job'),
    path('job/<int:job_id>/edit/', views.edit_job_view, name='edit_job'),
    path('application/<int:application_id>/re-analyze/', views.re_analyze_application_view, name='re_analyze_application'),
    path('invite/<int:application_id>/', views.send_interview_invitation_view, name='send_invitation'),
    path('notifications/', views.notification_list_view, name='notifications'),
    path('application/<int:application_id>/conduct-interview/', views.conduct_interview_view, name='conduct_interview'),
    path('job/<int:job_id>/generate-quiz/', views.generate_quiz_view, name='generate_quiz'),
    path('application/<int:application_id>/take-quiz/', views.take_quiz_view, name='take_quiz'),
    path('cv-review/', views.cv_review_view, name='cv_review'),
    path('recruitment-analytics/', views.recruitment_analytics_view, name='recruitment_analytics'),
]